### ISSUE TITLE
Scrolling issue with the new Reference drop-down

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1311]
translationCore Create - v1.5.0 build 154-e836e43.

When the Support Reference is added in a row using the drop-down and then scrolled down the page, the drop-down fields (support reference, chapter /verse) overlap with the scripture pane. See the screen capture:https://images.zenhubusercontent.com/191973535/17cbd84b-1b0b-484c-b36b-3feeafeaedba/screen_recording_2022_06_14_at_2_38_20_pm.mov

**Comment by superdav42** [comment]
It's just fixed on the RCL. I'll release it and update tc-create-app to use it.

**Comment by elsylambert** [comment]
Thanks @superdav42

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.5.0 build 156-5e3e8a9. Scrolling issue is resolved.

**Comment by birchamp** [comment]
if dropdown is dropped then scrolling still shows above the scripture @superdav42
